apiVersion: v1
kind: Pod
metadata:
  name: hello-pod-1
  namespace: roboshop
  
spec:
  # list of containers
  containers:
  - name: hello-pod-1
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80