apiVersion: v1
kind: lables
metadata:
   name: label-demo
   labels:
      course: Devops 
      Trainer: "appalaraju"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
     

