apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: appalaraju
      value: devops
    - name: joindevops
      value: 150hrs
    - name: mirtipati
      value: hello devops
    - name: training
      value: newly joindevops
    
