apiVersion: v1
kind: Pod
metadata:
  name: config-demo
spec:
  
  containers:
  - name: nginx
    image: nginx
    
    ports:
    - containerPort: 80
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: configmap-demo
          key: course
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: configmap-demo
          key: duration
    
           

           
      

     
    

    