apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: appalaraju
      valueFrom:
         configMapKeyRef:
           name: course-demo
           key: course

    - name: duration
      valueFrom:
         configMapKeyRef:
           name: course-demo
           key: duration
    
           

           
      

     
    

    